#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/down.jpg
fi

leftwm-command "UnloadTheme"

if [ -x "$(command -v xcompmgr)" ]; then
  kill xcompmgr
elif [ -x "$(command -v picom)" ]; then
  kill picom
elif [ -x "$(command -v compton)" ]; then
  kill compton
fi

kill dunst