#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# Set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# Set background
if [ -x "$(command -v feh)" ]; then
  # feh --randomize --bg-fill ~/Pictures/Wallpapers*
  feh --bg-scale "${SCRIPTPATH}/background.png"
fi

# Run dunst
if [ -x "$(command -v dunst)" ]; then
  dunst &
fi

# Start compositor
if [ -x "$(command -v xcompmgr)" ]; then
  xcompmgr -f -I 0.03 &
elif [ -x "$(command -v picom)" ]; then
  picom &
elif [ -x "$(command -v compton)" ]; then
  compton &
fi
