#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# Run utility applications
if [ -x "$(command -h lxsession)" ]; then
  lxsession
fi

# Set background
if [ -x "$(command -v feh)" ]; then
  # feh --randomize --bg-fill /home/USER/Pictures/Wallpapers*
  feh --bg-scale "${SCRIPTPATH}/background.png"
fi
