#!/bin/sh

DIR="$HOME/Videos"

check_dir () {
	if [ ! -d "$DIR" ]; then
		mkdir $DIR
	else 
		echo "$DIR already exists"
	fi
}

getdim() { xrandr | sed -n "s/\s*\([0-9]\+x[0-9]\+\).*\*.*/\1/p" ;}

updateicon() { \
	echo "$1" > /tmp/recordingicon
	pkill -RTMIN+9 "${STATUSBAR:-dwmblocks}"
}

killrecording() {
	recpid="$(cat /tmp/recordingpid)"
	kill -15 "$recpid"
	rm -f /tmp/recordingpid
	updateicon ""
	pkill -RTMIN+9 "${STATUSBAR:-dwmblocks}"
}

screencast() { \
	ffmpeg -y \
	-f x11grab \
	-framerate 30 \
	-s "$(getdim)" \
	-i "$DISPLAY" \
	-r 24 \
	-use_wallclock_as_timestamps 1 \
	-f alsa -thread_queue_size 1024 -i default \
	-c:v h264 \
	-crf 0 -preset ultrafast -c:a aac \
	"$DIR/screencast-$(date '+%y%m%d-%H%M-%S').mp4" &
	echo $! > /tmp/recordingpid
	echo $! > /tmp/recordingpid
	updateicon "⏺️🎙️"
}

video() { ffmpeg \
	-f x11grab \
	-framerate 30 \
	-s "$(getdim)" \
	-i "$display" \
	-c:v libx264 -qp 0 -r 30 \
	"$DIR/video-$(date '+%y%m%d-%h%m-%s').mkv" &
	echo $! > /tmp/recordingpid
	updateicon "⏺️"
}

audio() { \
	ffmpeg \
	-f alsa -i default \
	-c:a flac \
	"$DIR/audio-$(date '+%y%m%d-%H%M-%S').flac" &
	echo $! > /tmp/recordingpid
	updateicon "🎙️"
}

full_screenshot() { \
	sleep 1 # wait for rofi to close
	scrot -b '%Y:%m:%d:%H:%M:%S.png' -e 'mv $f ~/Pictures/'
}

rectangle_screenshot() { \
	scrot --select -b '%Y:%m:%d:%H:%M:%S.png' -e 'mv $f ~/Pictures/'
}

wayland_full_screenshot() { \
	sleep 1 # wait for wofi to close
	grimblast save
}

wayland_rectangle_screenshot() { \
	grimblast save area
}

option1="Screencast"
option2="Video"
option3="Audio"
option4="Stop recording"
option5="Screenshot full"
option6="Screenshot select"
option7="Exit"

if [ "$1" = "wayland" ]; then
	options="$option5\n$option6"
	choice=$(printf "$options" | wofi -i -d -no-sidebar-mode -L 3 -p " ") 
elif [ ! -f /tmp/recordingpid ] ; then
	options="$option1\n$option2\n$option3\n$option5\n$option6\n$option7"
	choice=$(printf "$options" | rofi -i -theme-str '@import "~/.config/leftwm/themes/current/rofi/record.rasi"' -dmenu -no-show-icons -no-sidebar-mode -lines 4 -width 30 -p " ") 
else
	options="$option4\n$option7"
	choice=$(printf "$options" | rofi -i -theme-str '@import "~/.config/leftwm/themes/current/rofi/record-stop.rasi"' -dmenu -no-show-icons -no-sidebar-mode -lines 4 -width 30 -p " ") 
fi

if [ "$1" = "wayland" ]; then
    case $choice in
        $option5) wayland_full_screenshot ;;
        $option6) wayland_rectangle_screenshot ;;
        *) exit ;;
    esac
else
    case $choice in
        $option1) screencast ;;
        $option2) video ;;
        $option3) audio ;;
        $option4) killrecording ;;
        $option5) full_screenshot ;;
        $option6) rectangle_screenshot ;;
        *) exit ;;
    esac
fi
